### PR TITLE
Allow starting unscheduled stories (via prompt or flag)

### PR DESCRIPTION
**Pull request by Naatan**
Use-case: https://activestate.slack.com/archives/C0KPWHDA7/p1547759506467500

---
This change is [Reviewable](https://reviewable.io/reviews/activestate/start-pt-story/3)

### CODE REVIEW

**Comment by autarch** [comment]
Is it necessary to offer both a flag and a prompt? I'm inclined to say that we should just always prompt, since presumably this is an uncommon situation.

**Comment by Naatan** [comment]
I'm using this to quickly resolve stories bugs that pop up. Could always prompt, but that makes my 1 step process a 2 step process, so I appreciate the flag. If anything the prompt can be dropped, I don't use it but figured it would be nice to have.

**Comment by autarch** [comment]
@Naatan Would you mind removing me from the requested reviewers on this one? It shows up when I'm looking for pending review work at my new employer, which is a bit confusing.

**Comment by Naatan** [comment]
@autarch But.. I was still clinging on to the hope that you might approve it!

**Pull request closed without merging**
